package recovery

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"

	"github.com/xtianxx/txharbor/internal/recovery/controlstore"
)

const (
	backupVerificationStartedAction  = "backup_verification_started"
	backupVerificationAcceptedAction = "backup_verification_accepted"
	backupVerificationLockDomain     = "txharbor:recovery:backup-verification-epoch:v1:"
)

// BackupVerificationEpoch is a committed revocation fence. Audit IDs are
// generated by recovery_audit itself and never supplied by a caller.
type BackupVerificationEpoch struct {
	BackupID    string
	AuditID     int64
	InputDigest string
}

type backupVerificationBinding struct {
	EpochID     int64
	EvidenceID  string
	EvidenceRef string
	Legacy      bool
}

// beginBackupVerificationEpoch commits a START before verification can mutate
// the manifest or isolated target. A later START supersedes every older
// accepted receipt for this backup_id, regardless of manifest digest.
func beginBackupVerificationEpoch(ctx context.Context, store *controlstore.Store, m *Manifest,
	verifier, operationID, instanceID, targetFingerprint, targetRole, programVersion string) (BackupVerificationEpoch, error) {
	if store == nil || store.Pool() == nil || m == nil || strings.TrimSpace(m.BackupID) == "" {
		return BackupVerificationEpoch{}, errors.New("verification epoch requires a parsed backup and control store")
	}
	manifestDigest, err := m.Digest()
	if err != nil {
		return BackupVerificationEpoch{}, fmt.Errorf("derive verification input digest: %w", err)
	}
	input := struct {
		Domain, BackupID, ManifestDigest, Verifier, OperationID, InstanceID string
		TargetFingerprint, TargetRole, ProgramVersion                       string
	}{backupVerificationLockDomain, m.BackupID, manifestDigest, verifier, operationID,
		instanceID, targetFingerprint, targetRole, programVersion}
	encoded, err := json.Marshal(input)
	if err != nil {
		return BackupVerificationEpoch{}, fmt.Errorf("encode verification epoch input: %w", err)
	}
	sum := sha256.Sum256(encoded)
	inputDigest := "sha256:" + hex.EncodeToString(sum[:])
	target, _ := json.Marshal(map[string]string{"backup_id": m.BackupID})
	detail, _ := json.Marshal(map[string]string{
		"input_digest": inputDigest, "manifest_digest": manifestDigest,
		"instance_id": instanceID, "target_fingerprint": targetFingerprint,
		"target_role_fingerprint": targetRole, "program_version": programVersion,
	})
	tx, err := store.Pool().Begin(ctx)
	if err != nil {
		return BackupVerificationEpoch{}, fmt.Errorf("begin backup verification epoch: %w", err)
	}
	defer func() { _ = tx.Rollback(context.Background()) }()
	if err := lockBackupVerificationEpoch(ctx, tx, m.BackupID); err != nil {
		return BackupVerificationEpoch{}, err
	}
	auditID, err := controlstore.WriteAuditReturningID(ctx, tx, controlstore.AuditRecord{
		Actor: verifier, Action: backupVerificationStartedAction, Target: target, Detail: detail,
		Result: controlstore.AuditOK, OperationID: operationID,
	})
	if err != nil {
		return BackupVerificationEpoch{}, fmt.Errorf("record verification epoch start: %w", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return BackupVerificationEpoch{}, fmt.Errorf("commit verification epoch start: %w", err)
	}
	return BackupVerificationEpoch{BackupID: m.BackupID, AuditID: auditID, InputDigest: inputDigest}, nil
}

func lockBackupVerificationEpoch(ctx context.Context, q controlstore.Queryer, backupID string) error {
	if strings.TrimSpace(backupID) == "" {
		return errors.New("backup verification epoch requires backup_id")
	}
	_, err := q.Exec(ctx, `SELECT pg_advisory_xact_lock(hashtextextended($1, 0))`, backupVerificationLockDomain+backupID)
	if err != nil {
		return fmt.Errorf("lock backup verification epoch: %w", err)
	}
	return nil
}

func latestBackupVerificationEpoch(ctx context.Context, q controlstore.Queryer, backupID string) (int64, error) {
	var epoch int64
	err := q.QueryRow(ctx, `SELECT audit_id FROM recovery_audit
WHERE action=$1 AND target->>'backup_id'=$2
ORDER BY audit_id DESC LIMIT 1`, backupVerificationStartedAction, backupID).Scan(&epoch)
	if errors.Is(err, pgx.ErrNoRows) {
		return 0, nil
	}
	if err != nil {
		return 0, fmt.Errorf("read latest backup verification epoch: %w", err)
	}
	return epoch, nil
}

func requireCurrentBackupVerificationEpoch(ctx context.Context, tx pgx.Tx, epoch BackupVerificationEpoch) error {
	if err := lockBackupVerificationEpoch(ctx, tx, epoch.BackupID); err != nil {
		return err
	}
	latest, err := latestBackupVerificationEpoch(ctx, tx, epoch.BackupID)
	if err != nil {
		return err
	}
	if latest != epoch.AuditID {
		return errors.New("backup verification epoch was superseded by a newer attempt")
	}
	return nil
}

// writeManifestForCurrentVerificationEpoch serializes brief manifest-state
// writes with START/ACCEPT. It prevents an older concurrent attempt from
// overwriting a newer attempt's state after the newer receipt is accepted.
func writeManifestForCurrentVerificationEpoch(ctx context.Context, store *controlstore.Store,
	epoch BackupVerificationEpoch, path string, m *Manifest) (bool, error) {
	tx, err := store.Pool().Begin(ctx)
	if err != nil {
		return false, fmt.Errorf("begin verification manifest publication: %w", err)
	}
	defer func() { _ = tx.Rollback(context.Background()) }()
	if err := lockBackupVerificationEpoch(ctx, tx, epoch.BackupID); err != nil {
		return false, err
	}
	latest, err := latestBackupVerificationEpoch(ctx, tx, epoch.BackupID)
	if err != nil {
		return false, err
	}
	if latest != epoch.AuditID {
		return false, nil
	}
	if err := writeVerifiedManifest(path, m); err != nil {
		return false, err
	}
	if err := tx.Commit(ctx); err != nil {
		return false, fmt.Errorf("commit verification manifest publication: %w", err)
	}
	return true, nil
}

func recordBackupVerificationAccepted(ctx context.Context, tx pgx.Tx, epoch BackupVerificationEpoch,
	manifestVersion, manifestDigest, evidenceID, evidenceRef, instanceID, actor string, generation int64) (int64, error) {
	if err := requireCurrentBackupVerificationEpoch(ctx, tx, epoch); err != nil {
		return 0, err
	}
	var evidenceExists bool
	if err := tx.QueryRow(ctx, `SELECT EXISTS (
SELECT 1 FROM recovery_evidence
WHERE evidence_id=$1::uuid
  AND instance_id IS NOT DISTINCT FROM NULLIF($2, '')::uuid
  AND generation=$3 AND kind='backup_manifest'
  AND artifact_hash=$4 AND artifact_ref=$5
  AND scope->>'backup_id'=$6 AND scope->>'manifest_version'=$7
  AND scope->>'manifest_digest'=$4 AND scope->>'verification_epoch'=$8
)`, evidenceID, instanceID, generation, manifestDigest, evidenceRef, epoch.BackupID,
		manifestVersion, fmt.Sprint(epoch.AuditID)).Scan(&evidenceExists); err != nil {
		return 0, fmt.Errorf("validate inserted backup verification evidence: %w", err)
	}
	if !evidenceExists {
		return 0, errors.New("backup verification acceptance has no matching evidence row")
	}
	target, err := json.Marshal(map[string]any{
		"backup_id": epoch.BackupID, "epoch_id": epoch.AuditID,
		"manifest_version": manifestVersion, "manifest_digest": manifestDigest,
	})
	if err != nil {
		return 0, err
	}
	detail, err := json.Marshal(map[string]any{
		"verification_epoch": epoch.AuditID, "evidence_id": evidenceID,
		"evidence_ref": evidenceRef, "manifest_digest": manifestDigest,
	})
	if err != nil {
		return 0, err
	}
	return controlstore.WriteAuditReturningID(ctx, tx, controlstore.AuditRecord{
		InstanceID: instanceID, Actor: actor,
		Action: backupVerificationAcceptedAction, Target: target, Detail: detail,
		Result: controlstore.AuditOK, EvidenceGeneration: &generation,
	})
}

// currentBackupVerificationBinding returns only a receipt paired to the latest
// committed START and the exact evidence row. Legacy evidence is accepted only
// when this backup has never entered the epoch journal.
func currentBackupVerificationBinding(ctx context.Context, q controlstore.Queryer, instanceID string,
	m *Manifest, digest string) (backupVerificationBinding, bool, error) {
	latest, err := latestBackupVerificationEpoch(ctx, q, m.BackupID)
	if err != nil {
		return backupVerificationBinding{}, false, err
	}
	if latest == 0 {
		return backupVerificationBinding{Legacy: true}, true, nil
	}
	var evidenceID, evidenceRef string
	err = q.QueryRow(ctx, `SELECT e.evidence_id::text, a.detail->>'evidence_ref'
FROM recovery_audit a
JOIN recovery_evidence e ON e.evidence_id::text = (a.detail->>'evidence_id')
WHERE a.action=$1
	AND a.result='ok'
  AND a.instance_id IS NOT DISTINCT FROM NULLIF($2, '')::uuid
  AND a.target->>'backup_id'=$3
  AND a.target->>'epoch_id'=$4
  AND a.target->>'manifest_version'=$5
  AND a.target->>'manifest_digest'=$6
  AND a.detail->>'verification_epoch'=$4
  AND a.detail->>'manifest_digest'=$6
  AND a.detail->>'evidence_ref' IS NOT NULL
  AND e.instance_id IS NOT DISTINCT FROM NULLIF($2, '')::uuid
  AND a.evidence_generation IS NOT DISTINCT FROM e.generation
  AND e.kind='backup_manifest'
  AND e.artifact_hash=$6 AND e.artifact_ref=(a.detail->>'evidence_ref')
  AND e.scope->>'backup_id'=$3
  AND e.scope->>'manifest_version'=$5
  AND e.scope->>'manifest_digest'=$6
  AND e.scope->>'verification_epoch'=$4
ORDER BY a.audit_id DESC LIMIT 1`, backupVerificationAcceptedAction, instanceID,
		m.BackupID, fmt.Sprint(latest), m.ManifestVersion, digest).Scan(&evidenceID, &evidenceRef)
	if errors.Is(err, pgx.ErrNoRows) {
		return backupVerificationBinding{}, false, nil
	}
	if err != nil {
		return backupVerificationBinding{}, false, fmt.Errorf("validate current verification receipt: %w", err)
	}
	return backupVerificationBinding{EpochID: latest, EvidenceID: evidenceID, EvidenceRef: evidenceRef}, true, nil
}

// BackupVerificationReceiptCurrent validates the receipt used by successful
// CLI idempotency replay without invoking PostgreSQL client tools.
func BackupVerificationReceiptCurrent(ctx context.Context, store *controlstore.Store, backupID, instanceID,
	manifestVersion, digest, evidenceRef string, acceptedAuditID int64) (bool, error) {
	if store == nil || store.Pool() == nil {
		return false, errors.New("verification receipt lookup requires control store")
	}
	tx, err := store.Pool().Begin(ctx)
	if err != nil {
		return false, fmt.Errorf("begin verification receipt lookup: %w", err)
	}
	defer func() { _ = tx.Rollback(context.Background()) }()
	if err := lockBackupVerificationEpoch(ctx, tx, backupID); err != nil {
		return false, err
	}
	latest, err := latestBackupVerificationEpoch(ctx, tx, backupID)
	if err != nil || latest == 0 {
		return false, err
	}
	var found bool
	err = tx.QueryRow(ctx, `SELECT EXISTS (
SELECT 1 FROM recovery_audit a
JOIN recovery_evidence e ON e.evidence_id::text = (a.detail->>'evidence_id')
WHERE a.action=$1 AND a.instance_id IS NOT DISTINCT FROM NULLIF($2, '')::uuid
	AND a.result='ok'
 AND a.target->>'backup_id'=$3 AND a.target->>'epoch_id'=$4
 AND a.target->>'manifest_version'=$5 AND a.target->>'manifest_digest'=$6
 AND a.detail->>'verification_epoch'=$4 AND a.detail->>'evidence_ref'=$7
 AND a.detail->>'manifest_digest'=$6
 AND e.instance_id IS NOT DISTINCT FROM NULLIF($2, '')::uuid AND e.kind='backup_manifest'
	AND a.evidence_generation IS NOT DISTINCT FROM e.generation
 AND e.artifact_hash=$6 AND e.artifact_ref=$7
 AND e.scope->>'backup_id'=$3 AND e.scope->>'manifest_version'=$5
 AND e.scope->>'manifest_digest'=$6 AND e.scope->>'verification_epoch'=$4
 AND a.audit_id=$8
)`, backupVerificationAcceptedAction, instanceID, backupID, fmt.Sprint(latest), manifestVersion, digest, evidenceRef, acceptedAuditID).Scan(&found)
	if err != nil {
		return false, fmt.Errorf("validate current verification receipt: %w", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return false, fmt.Errorf("commit verification receipt lookup: %w", err)
	}
	return found, nil
}
